-- PRODUCT ANALYSIS

-- Task 1 – Product Portfolio Overview

-- Task 1.1 Total Products
SELECT COUNT(*) AS Total_products
FROM Products;

-- Total products = 32951

-- Task 1.2 Total Categories
SELECT COUNT(DISTINCT(product_category_name)) AS Total_categories
FROM Products;

-- Total categories = 73

-- Task 1.3 Products per categories
SELECT PC.column2 AS Product_category,
       COUNT(P.Product_id) AS Products_per_category
FROM Products AS P
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Products_per_category DESC;

-- Insghts
-- Bed and Bath category has most products = 3029 , followed by sports(2867) and furniture(2657).
-- CDs , security and services , home comfort , these categories have least products.


-- Task 2 – Best-Selling Product Categories

-- Task 2.1 Units sold per categories
SELECT PC.column2 AS Product_category,
       COUNT(OI.order_id) AS Orders_per_category
FROM Order_items AS OI
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Orders_per_category DESC;

-- Insights
-- Most number of orders is from Bed and Bath category '11115' orders, followed by health (9670) and sports(8641) categories.
-- Security and Services (2) ,fashion children(8) and CDs and DvDs (14) , these categories have lowest orders.

-- Task 2.2 Revenue per category
WITH OrderItemCount AS 
(SELECT order_id, 
        COUNT(*) AS Item_count
 FROM Order_items
 GROUP BY order_id )
SELECT PC.column2 AS Product_category,
       SUM(OP.payment_value / OIC.item_count) AS Revenue_per_category
FROM Order_items AS OI
JOIN OrderItemCount AS OIC
ON OI.order_id = OIC.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
JOIN Order_payments AS OP
ON OI.order_id = OP.order_id
GROUP BY PC.column2
ORDER BY Revenue_per_category DESC;

/* Insights
1.Health and Beauty is the highest revenue-generating category with USD 1.44M.
It is followed by Watches and Gifts (USD 1.30M) and Bed Bath Table (USD 1.24M).

2.Categories such as Security and Services (USD 325), Fashion Children's Clothes (USD 677), CDs/DVDs/Musicals (USD 954),
Flowers (USD 1.56K), and Arts and Craftsmanship (USD 2.18K) contribute only a tiny fraction of total revenue.
*/

-- Task 2.3 Revenue share(%) per category
WITH OrderItemCount AS 
( SELECT order_id,
         COUNT(*) AS Item_counts
  FROM Order_items
  GROUP BY order_id )

SELECT PC.column2 AS Product_category,
       SUM(OP.payment_value / OIC.Item_counts) AS Revenue_per_category,
       ROUND(SUM(OP.payment_value / OIC.Item_counts) * 100 /  SUM(SUM(OP.payment_value  / OIC.Item_counts)) OVER(),2) AS Revenue_share
FROM Order_items AS OI
JOIN OrderItemCount AS OIC
ON OI.order_id = OIC.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
JOIN Order_payments AS OP
ON OI.order_id = OP.order_id
GROUP BY PC.column2
ORDER BY Revenue_per_category DESC;

-- Insights 
-- Over 60 % of generated by Top 10 categories
-- More than 40 categories each contribute less than 1% of total revenue.

/* Business Recommendation
1. Maintain optimal inventory levels for high-demand categories to avoid stockouts.
2. Prioritize these categories in marketing campaigns and seasonal promotions.
3. Expand the product assortment within top-performing categories to capture additional demand.
*/


--Task 3 – Product Category Performance

WITH OrderItemCount AS 
( SELECT order_id,
         COUNT(*) AS Item_counts
  FROM Order_items
  GROUP BY order_id )

SELECT PC.column2 AS Product_category,
       COUNT(OI.order_id) AS Total_order,
       AVG(OI.freight_value) AS Avg_shipping_cost,
       AVG(OI.price) Avg_price,
       SUM(OP.payment_value / OIC.Item_counts) AS Revenue_per_category
FROM Order_items AS OI
JOIN OrderItemCount AS OIC
ON OI.order_id = OIC.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
JOIN Order_payments AS OP
ON OI.order_id = OP.order_id
GROUP BY PC.column2
ORDER BY Total_order DESC;

/* Insights
1. Premium categories include - Computers , Small appliances home oven and coffee, Home appliances , Agro industry and commerce.

2. Categories like Bed Bath, Furniture decor , Housewares and Telephony do not have high prices but generate revenue through sheer volume.
*/


--Task 4 – High Revenue vs High Volume

WITH CategorySales AS
( SELECT PC.column2 AS Product_category,
         SUM(OP.payment_value) AS Total_revenue,
         COUNT(*) AS Units_sold,
         ROUND(SUM(OP.payment_value) * 1.0 /COUNT(*) ,2) AS Revenue_per_unit
 FROM Order_items AS OI
 JOIN Order_payments AS OP 
 ON OI.order_id = OP.order_id
 JOIN Products  AS P
 on OI.product_id = P.product_id
 JOIN Product_category AS PC
 ON P.product_category_name = PC.column1
 GROUP BY PC.column2)
 SELECT * ,
       CASE
            WHEN Revenue_per_unit > 200 THEN 'Premium product category'
            WHEN Revenue_per_unit BETWEEN '99' AND '199' THEN 'Balanced'
            ELSE 'Volume  driven'
END AS Observation
FROM CategorySales
ORDER BY Total_revenue DESC;

-- Categories like Watches , Office furniture ,Computers generate revenue because of high prices.

-- categories like Electronics , Food rely on volumes to boost theie revenue

/* Business Recommendation
1. For premium categories, focus on premium branding, customer experience, and value-added services.
2. For volume-driven categories, optimize pricing and inventory turnover to maximize sales.
3. Use different marketing strategies for premium and volume-based categories.
*/


-- Task 5 – Product Price Analysis

SELECT 
      PC.column2 AS Product_category,
      MIN(OI.price) AS Min_price,
      MAX(OI.price) AS Max_price,
      AVG(OI.price) AS Avg_price
FROM Order_items AS OI
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category PC
ON p.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Max_price DESC;

-- Computers , Small appliances home oven and coffee, Home appliances , Agro industry and commerce have the highest average price.
-- Houseware , computers and art have the Highest price 
/* Business Recommendation
1. Review pricing strategies for expensive products with low sales.
2. Test promotional pricing or installment payment options to improve conversion.
3. Regularly benchmark prices against competitors to remain competitive.
*/


-- Task 6 – Freight Cost Analysis

-- Task 6.1 Average Freight value per Product category
SELECT PC.column2 AS Product_cataegory,
       AVG(OI.freight_value) AS Avg_freight_value
FROM Order_items AS OI
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Avg_freight_value DESC;

/* Insights
1. Computers category has most Average freight value - USD 48.5, followed closely by Home appliances(USD 44) , Furniture and Mattress(USD 42.9) .

2. Fashion clothes and Books have least Average freight value 'USD 11.9' and 'USD 12.8' respectively.
*/

-- Task 6.2 Freight as percentage of Product price

SELECT PC.column2 AS Product_cataegory,
       AVG(OI.freight_value) AS Avg_freight_value,
       ROUND(AVG(OI.freight_value *100 / OI.price) ,2 ) AS Avg_freight_percentage
FROM Order_items AS OI
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Avg_freight_percentage DESC;
/* Insights
1. Categories with the highest freight percentage(Home Comfort(93%) , Electronics(68%) are expensive to ship relative to their selling price.

2. High freight ratios may reduce profit margins and discourage customer purchases.

3. Lightweight, high-value categories(Computers(5.6%) , Watches(17%) usually have a much lower freight percentage.
*/

/* Business Recommendation
1. Negotiate shipping rates with logistics partners for heavy or bulky products.
2. Review packaging to reduce shipping weight and dimensions.
3. Offer free shipping only for products that can absorb the additional cost.
*/


-- Task 7 – Product Ratings

-- Task 7.1 Which categories recieves the highest review scores?
SELECT PC.column2 AS Product_cataegory,
       COUNT(ORs.review_score) AS Total_reviews,
       Avg(ORs.review_score) AS Avg_review_score
FROM Order_items AS OI
JOIN Order_reviews AS ORs
ON OI.order_id = ORs.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Total_reviews DESC;

/* Insights
1. High customer satisfaction in major product categories :-
Health & Beauty,  Sports & Leisure, Housewares, Watches & Gifts
These categories have both high customer engagement and consistently positive reviews, making them strong performers for revenue generation and customer retention.

2. Customer trust is strongest in lifestyle and everyday-use products
Health & Beauty, Housewares, Auto, Baby
Frequently purchased products consistently meet customer expectations, suggesting reliable product quality and fulfillment.

3.Many niche categories such as:
Books (General Interest, Technical, Imported), Christmas Supplies, Flowers, Arts & Craftsmanship also received an average rating of 4.
*/

-- Task 7.2 Are expensive products rated better?
SELECT PC.column2 AS Product_cataegory,
       AVG(Oi.price) AS Avg_price,
       COUNT(ORs.review_score) AS Total_reviews,
       Avg(ORs.review_score) AS Avg_review_score
FROM Order_items AS OI
JOIN Orders AS O
ON OI.order_id = O.order_id
JOIN Order_reviews AS ORs
ON OI.order_id = ORs.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2
ORDER BY Avg_price DESC ;
/* Insights
1. Many expensive categories(Computers, Small Appliances Home Oven and Coffee, Home Appliances, Agro Industry And Commerce) recieves 4 star rating.

2.Some expensive categories (Fixed Telephony, Construction Tools Safety, Air Conditioning) recieves review rating of 3.
*/

-- Task 7.3 Do low-rated categories have delivery problem?
SELECT PC.column2 AS Product_cataegory,
       O.order_status,
       AVG(ORs.review_score) AS Avg_review_score
FROM Order_items AS OI
JOIN Orders AS O
ON OI.order_id = O.order_id
JOIN Order_reviews AS ORs
ON OI.order_id = ORs.order_id
JOIN Products AS P
ON OI.product_id = P.product_id
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
GROUP BY PC.column2 , O.order_status
HAVING AVG(ORs.review_score) < 3
ORDER BY Product_cataegory DESC;

/* Insights
1. Orders with order status cancelled has recieved 1 star review, indicating that cancelled orders contribute to most 1 star review.

2. Early-stage or unsuccessful orders - Lower ratings
   Successfully completed deliveries - Higher ratings

3. Orders still in the processing or invoiced stages show low average ratings.
*/

/* Business Recommendation
1. Investigate negative reviews to identify recurring quality or delivery issues.
2. Work with suppliers to improve product quality.
3. Improve product descriptions and images to better match customer expectations.
*/


-- Task 8 – Product Revenue Concentration

WITH CategoryRevenue AS
(
    SELECT
        PC.column2 AS Product_category,
        SUM(OI.price + OI.freight_value) AS Revenue_per_category
    FROM Order_items OI
    JOIN Products P
        ON OI.product_id = P.product_id
    JOIN Product_category PC
        ON P.product_category_name = PC.column1
    GROUP BY PC.column2
)

SELECT
    Product_category,
    Revenue_per_category,
    ROUND(Revenue_per_category * 100.0 /SUM(Revenue_per_category) OVER (),2) AS Revenue_share,
    ROUND(
        SUM(Revenue_per_category) OVER (
            ORDER BY Revenue_per_category DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) * 100.0 /SUM(Revenue_per_category) OVER (), 2)
            AS Cumulative_revenue_percentage
FROM CategoryRevenue
ORDER BY Revenue_per_category DESC;

/*
-- Pareto Analysis
Pareto analysis reveals that revenue on the Olist marketplace is highly concentrated.
Approximately 24% of product categories (17 out of 71) generate 80.86% of total revenue, demonstrating a clear Pareto distribution.
The top five categories alone contribute nearly 40% of total marketplace revenue, led by Health & Beauty (9.22%), Watches & Gifts (8.35%), and Bed Bath Table (7.94%).
This concentration suggests that business growth and profitability depend heavily on a relatively small group of high-performing categories,
while the majority of categories contribute only marginally to overall revenue.
Many categories contribute less than 0.2% of total revenue individually, including:
Flowers, Home Comfort 2, CDs/DVDs/Musicals, Fashion Children's Clothes, Security & Services
Collectively, these categories represent a long tail of low-revenue products.
*/

/* Business Recommendation
1. Continue investing in high-performing categories while avoiding excessive dependence on them.
2. Develop growth strategies for mid-performing categories to diversify revenue sources.
3. Monitor category performance regularly to detect changes in customer demand.
*/


--Task 9 – Slow-Moving Categories

-- Task 9.1 Which categories have many products but low sales?
SELECT PC.column2 AS Product_category,
       COUNT(DISTINCT(P.product_id)) AS Total_products,
       COUNT(Oi.order_id) AS Total_orders
FROM Products AS P
JOIN Product_category AS PC
ON P.product_category_name = PC.column1
JOIN Order_items AS OI
ON P.product_id = OI.product_id
GROUP BY PC.column2
ORDER BY Total_products DESC;

SELECT P.product_id,
       SUM(OP.payment_value) AS Total_revenue
FROM Products AS P
JOIN Order_items AS OI
ON P.product_id = OI.product_id
JOIN Order_payments AS OP
ON OI.order_id = OP.order_id
GROUP BY P.product_id
ORDER BY Total_revenue DESC;

/* Insights
1. Fashion Bags & Accessories
849 products
2,031 orders
2.39 orders per product
This category has one of the largest assortments but relatively weak demand. It may contain many slow-moving SKUs.

2. Home Construction
225 products
604 orders
2.68 orders per product
Customer demand is limited compared with the size of the catalog, suggesting opportunities to streamline the product range.

3. Toys
1,411 products
4,117 orders
2.92 orders per product
Although the category is popular overall, the large assortment means demand is spread across many products. Identifying best-selling and slow-moving toys could improve inventory efficiency.
*/

/*  Categories to Review (Large assortment, relatively low demand)

These categories have many products but comparatively low customer demand, suggesting possible over-assortment or slow-moving inventory.

Category	                      Why it should be reviewed
Fashion Bags & Accessories	      Large catalog (849 products) but only 2,031 orders.
Home Construction	              225 products with just 604 orders.
Fashion Male Clothing	          Low demand relative to the number of products.
Fashion Underwear Beach	          Weak order volume despite a reasonable assortment.


  Categories to Promote (Good demand and proven customer interest)

These categories already perform well and are good candidates for additional marketing investment.

Category	                    Why it should be promoted
Health & Beauty	                Highest revenue share (9.22%), strong order volume, good customer ratings.
Sports & Leisure	            High demand and revenue with positive customer feedback.
Watches & Gifts	                Strong revenue contribution and consistent sales.
Housewares	                    High order volume and customer satisfaction.
Garden Tools	                Strong orders relative to its product assortment.


Business Recommendation
1. Reduce inventory holding costs by discontinuing low-demand products.
2. Bundle slow-moving products with popular items to increase sales.
3. Consider targeted marketing campaigns before removing products from the catalog.
*/
